### ISSUE TITLE
v1 各模块设计和实现

### ISSUE THREAD

**Issue by 63isOK** [fight100year/golearn#13]

**Comment by 63isOK** [comment]
![kurento-go v1 0设计](https://user-images.githubusercontent.com/45553405/61921991-98315780-af91-11e9-9a0b-d4a814421fbf.png)

变更请看[这里](https://www.draw.io/?mode=github#H63isOK%2Fconference_graph%2Fmaster%2Fgraph%2Fkurento-client-go)

**Comment by 63isOK** [comment]
模块的设计对应着:
![image](https://user-images.githubusercontent.com/45553405/61922131-02e29300-af92-11e9-8883-bc229506c1a3.png)
#8

**Comment by 63isOK** [comment]
#14

**Comment by release4go** [comment]
实现时,需要考虑将业务api和kms api合并成一个
